# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ hexo ]
  pull_request:
    branches: [ hexo ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'
      GH_REF: github.com/menghuu/menghuu.github.io.git  #设置GH_REF
      NODE_VERSION: 14
    steps:
    - uses: actions/checkout@v2
    - name: setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "${{ env.NODE_VERSION }}"
        cache: 'npm'
    - name: install packages
      run: |
        npm install -g hexo
        npm install
    - run: npm list # test
    - name: generate static pages
      run: |
        hexo cl
        hexo g
    - name: git commit
      run: |
        cd ./public
        git init
        git config user.name "meng.hu"
        git config user.email "mail@meng.hu"
        git add .
        git commit -m "Site deployed by Github Action"
    - run: echo "${{ env.GH_REF }}"
    #- run: git push --force --quiet "https://${{ env.ACTION_GH_TOKEN }}@${{ env.GH_REF }}" master:master
    
