name: Github pages

on:
  push:
    branches: [ hugo ]
  pull_request:
    branches: [ hugo ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'
      GH_REF: github.com/menghuu/menghuu.github.io.git  #设置GH_REF
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - uses: peaceiris/actions-hugo@v2
      - name: Build
        run: hugo --minify
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/hugo' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public