# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ hexo ]
  pull_request:
    branches: [ hexo ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'
      GH_REF: github.com/menghuu/menghuu.github.io.git  #设置GH_REF
      NODE_VERSION: 14
    steps:
    - uses: actions/checkout@v2
    - name: setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${NODE_VERSION}
        cache: 'npm'
    - run: npm install
    - run: hexo cl
    - run: hexo g
    - run: cd ./public
    - run: git init
    - run: git config user.name "meng.hu"
    - run: git config user.email "mail@meng.hu"
    - run: git add .
    - run: git commit -m "Site deployed by Github Action"
    - run: echo "${GH_REF}"
    #- run: git push --force --quiet "https://${ACTION_GH_TOKEN}@${GH_REF}" master:master
    
